const projectData = [
  {
    title: 'M.I.K Előtető',
    titleAccent: '',
    roles: 'Webfejlesztés',
    duration: '2026 Május',
    tools: 'React.js',
    status: 'Kész',
    featured: true,
    summary: 'A vállalkozónak nem volt weboldala eddig. A megbízás célja az volt hogy készítsek egy olyan weboldalt ami átlátható, bizalmat keltő és egyszerű.',
    motivation: 'Egy modern, gyors és mobilbarát weboldal, ami jól tükrözi a vállalkozás profilját és segíti az ügyfélszerzést. Apró animációkkal fűszereztem hogy fentartsa az érdeklődők figyelmét. A weboldalnak egyetlen célja van: a kapcsolatfelvétel',
    url: 'mikeloteto.hu',
    images: ['/projects/mik-eloteto/mikeloteto_1.jpg', '/projects/mik-eloteto/mikeloteto_2.jpg', '/projects/mik-eloteto/mikeloteto_3.jpg'],
  },
  {
    title: 'Mooira',
    titleAccent: '',
    roles: 'Webfejlesztés',
    duration: '2026 Június',
    tools: 'Next.js',
    status: 'Folyamatban',
    featured: false,
    summary: 'Esküvői ruhavarró vállalkozó régi weboldalát kellett felújítani, modernizálni, újjáépíteni. A cél egy letisztult, könnyen navigálható és gyors weboldal létrehozása volt, amely jól mutatja be a vállalkozás szolgáltatásait és referenciáit.',
    motivation: 'TODO',
  },
  {
    title: 'StillSoul Production',
    titleAccent: '',
    roles: 'Webfejlesztés',
    duration: '2026 Július',
    tools: 'Next.js',
    status: 'Előkészítés alatt',
    featured: false,
    summary: 'Média ügynökségnek még nem volt weboldala, a megbízás célja egy olyan weboldal létrehozása volt, ami professzionális megjelenést biztosít, bemutatja a szolgáltatásokat és referenciákat, valamint megkönnyíti a kapcsolatfelvételt az ügyfelekkel.',
    motivation: 'TODO',
  },
    {
    title: 'Hideg email automatizáló asszisztens',
    titleAccent: '',
    roles: 'AI automatizáció',
    duration: '2026 Május',
    tools: 'Claude code, Apify API, Notion API, Resend API',
    status: 'Kész',
    featured: true,
    summary: 'Sok időt elvesz az embertől a hideg email kampányok előkészítése, megírása, kiküldése. Ezért szükségem volt egy olyan eszközre amely ezt lerövidíti és észben tartja helyettem.',
    motivation: 'Sikerült létrehoznom egy olyan eszközt amely megkeresi a megadott iparágban a potenciális ügyfeleket, kiküldi helyettem az emailt, es egy Notion adatbázisban számontartja hogy az adott kontakt melyik státuszban van. Ezáltal sokkal hatékonyabban tudok hideg email kampányokat indítani, és több potenciális ügyfelet érhetek el kevesebb időráfordítással. Nagyjából a napi 2-3 órás keresést és emailezést rövidítette le 1 perc-re.',
    images: ['/projects/cold-email-sender/email-sender1.png', '/projects/cold-email-sender/email-sender2.png','/projects/cold-email-sender/email-sender3.png'],
   },
    {
    title: 'Ticketing rendszer AI integráció',
    titleAccent: '',
    roles: 'AI automatizáció',
    duration: '2026 Április',
    tools: 'Node Red, Otobo.io, Gemini API',
    status: 'Kész',
    featured: true,
    summary: 'Ticketing rendszerbe szerettek volna egy olyan megoldást amely automatikusan kategorizál, átnevez, és összefoglalót gyárt. Napi 100+ hibajegynél ezek az apró feladatok rengeteg időt elvesznek, és megnehezítik a gyors reagálást a bejövő hibajegyekre.',
    motivation: 'Implementáltam egy olyan megoldást amely a bejövő hibajegyeket automatizáltan kategorizálja, és a tartalma alapján összefoglalja a címét a hibajegynek. Ezen kívül hosszú levelezések esetén kérhető egy rövid pár mondatos összefoglaló a teljes levelezésről. Ezáltal sokkal gyorsabban tudják átlátni a bejövő hibajegyeket, és hatékonyabban tudják kezelni őket. Ezzel a megoldással havi 20 órát is megtakaríthatnak fejenként',
  },
]

export const projects = projectData.map((p, i) => ({
  ...p,
}))